# This Workflow performs a full release of Che
name: Release - Orchestrate Overall Release Phases
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version that is going to be released. Should be in format 7.y.z'
        required: true
        default: ''

jobs:
  test-release:
    runs-on: ubuntu-16.04
    steps:
    - uses: mkuznyetsov/trigger-workflow-action@next
      with:
        owner: eclipse
        repo: che-release
        github_token: ${{ secrets.CHE_BOT_GITHUB_TOKEN }}
        workflow_id: "4300579"
        workflow_name: "Release - Orchestrate Overall Release Phases"
        version: "${{ github.event.inputs.version }}"
        wait_interval: "2"
        wait_timeout: "20"