# This Workflow announces a release in Eclipse Mattermost to https://mattermost.eclipse.org/eclipse/channels/eclipse-che-releases
name: Release - Send mattermost notification
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version that is going to be announced. Should be in format 7.y.z'
        required: true
        default: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create message
      run: |
        echo "{\"text\":\":che-logo: First post!\"}" > mattermost.json
    - name: Send message
      uses: mattermost/action-mattermost-notify@master
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        MATTERMOST_CHANNEL: eclipse-che-ci
        MATTERMOST_USERNAME: che-bot
